### ISSUE TITLE
Extension settings unreadable using Firefox dark theme

### ISSUE THREAD

**Issue by glenneroo** [plibither8/refined-hacker-news#71]
As seen in screenshot:
![image](https://user-images.githubusercontent.com/1424173/73121191-e68ed580-3f77-11ea-93b9-eabe2959be48.png)

To enable dark theme, menu > customize > theme (very bottom) > dark theme.

**Comment by plibither8** [comment]
Thanks for pointing this out, will look into it.

**Comment by plibither8** [comment]
Hi @glenneroo, @sjuxax. I was not able to reproduce this on my system, but I've pushed a style file ([webext-base.css](src/webext-base.css)) that should fix this. Please do update!

**Comment by glenneroo** [comment]
Did you push the update to the Firefox plugin or do I have to manually install the css file somewhere?

I tried via Firefox update mechanism but it says there are no updates:
![image](https://user-images.githubusercontent.com/1424173/78457515-f8dd6c00-76aa-11ea-878b-3f1ce1a00735.png)

Or does it silently update when after restarting my browser?

**Comment by plibither8** [comment]
I pushed the update to Mozilla Add-ons, and Firefox should ideally silently update your extension. The latest version is 20.4.4, is that the one you have installed?

**Comment by glenneroo** [comment]
I'm on 20.4.4 and it's still unfortunately the same. Did you set your FireFox to dark theme? Otherwise I guess it's one of my many extensions.

**Comment by plibither8** [comment]
That's unfortunate :(

I still have not been able to reproduce this on my machine -- I'm using Firefox 74.0.1 on Linux Ubuntu 18.04. What's your system info?

**Comment by glenneroo** [comment]
Half the battle of fixing bugs is being able to reproduce them ;)

Firefox 74.0.1 on Windows 10.

Here's a list of my extensions:
Name 	Version 	Enabled 	ID
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
Decentraleyes	2.0.14	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	1.0	true	ddg@search.mozilla.org
DuckDuckGo Privacy Essentials	2019.12.12	true	jid1-ZAdIEUB7XOzOJw@jetpack
Enhancer for YouTube™	2.0.101	true	enhancerforyoutube@maximerf.addons.mozilla.org
Film scores for Netflix	0.9.1	true	{6babe29b-f164-4a56-8081-06f939062cdb}
Firefox Multi-Account Containers	6.2.3	true	@testpilot-containers
Forest: stay focused, be present	3.11.0	true	@forest-firefox-addon
Fraidycat	1.1.3	true	{94060031-effe-4b93-89b4-9cd570217a8d}
Free Download Manager	3.0.49	true	fdm_ffext2@freedownloadmanager.org
Google	1.0	true	google@search.mozilla.org
Google Translator for Firefox	3.0.3.3	true	translator@zoli.bod
LastPass: Free Password Manager	4.45.0.5	true	support@lastpass.com
Panel View for Google™ Translate	0.4.3	true	jid0-fbHwsGfb6kJyq2hj65KnbGte3yT@jetpack
Privacy Badger	2020.2.19	true	jid1-MnnxcxisBPnSXQ@jetpack
Reddit Enhancement Suite	5.18.11	true	jid1-xUfzOsOFlzSOXg@jetpack
Refined Hacker News	20.4.4	true	refinedhackernews@mihir.ch
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.26.0	true	uBlock0@raymondhill.net
Unpaywall	3.91	true	{f209234a-76f0-4735-9920-eb62507a54cd}
Weather	4.3.252	true	{a79a9c4c-9c3f-4bf4-9e58-6574cc0b7ecb}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Ratings Preview for YouTube™	6.1.5	false	jid0-G6461UajDjhNAwSukoedlkhD0XA@jetpack

**Comment by sjuxax** [comment]
Not fixed here either on Firefox 75b12 or Firefox 76b1 on Win10, nor Firefox 75b12 on Ubuntu 18.10 (haven't tested 76b1). Backticks work though. 😉 🎉

If you don't beat me to it @plibither8, I'll try to debug sometime this week and see if I can see what's going on. I did check the extension debug view briefly and saw some path errors, but didn't do anything more than a superficial glance so they may be related to something else, like installing the temporary extension incorrectly. 😅

**Comment by plibither8** [comment]
Thanks for the details @glennero!

@sjuxax that would be great since I'm not able to reproduce on my machine. Hopefully you'll be able to work it out :D. Thanks!

**Comment by lookfirst** [comment]
Using Brave, I just noticed it... `20.4.4`

![image](https://user-images.githubusercontent.com/85355/78942738-25103880-7a6f-11ea-9877-b7f3823b0c5d.png)

**Comment by plibither8** [comment]
Hi @glenneroo, @sjuxax. I've merged #76 (thanks @lookfirst!) which should fix the issue. I've published the update on the marketplaces (v20.4.14) too.

**Comment by glenneroo** [comment]
Still unfortunately happening on my end with 20.4.14 and after restarting my browser.

**Comment by plibither8** [comment]
I'll try to debug this on my Win10 Firefox tonight when I get time. Thanks for pointing it out.

**Comment by lookfirst** [comment]
darn that it doesn't fix FF... .14 hasn't hit chromestore yet so i can't confirm it is fixed there...

**Comment by plibither8** [comment]
Chrome will take a week or two to update - they're review process takes time, especially during these days.

**Comment by lookfirst** [comment]
That's insane... =) 

Is it possible to easily clone the repo and load it as a dev extension?

**Comment by plibither8** [comment]
I can send over the "dist/" directory zipped, and you can load it up on your machine. How's that?

**Comment by plibither8** [comment]
[20.4.14.zip](https://github.com/plibither8/refined-hacker-news/files/4476099/20.4.14.zip)

You can unzip this and proceed! :)

**Comment by lookfirst** [comment]
Thanks! It is fixed in Chrome now. Silly me... loading the extension that way, removed my settings though. =( oh well!

**Comment by plibither8** [comment]
Ahh that's unfortunate :/
Thanks for reviewing it though! :)

**Comment by Forbo** [comment]
I'm also getting this in Firefox on Ubuntu. I'm using the "Default" Firefox theme with Gnome Tweaks' "Adwaita-dark" applications theme.
![image](https://user-images.githubusercontent.com/6404250/101527673-8ca6bc80-394b-11eb-99b7-c9aa312a996e.png)

**Comment by glenneroo** [comment]
This issue is also related to a DarkReader firefox plugin bug-report I just submitted: https://github.com/darkreader/darkreader/issues/5512#issuecomment-817168290

After disabling Refined-Hacker-News, I can once again read code blocks normally, which are otherwise white text on white background, the same as this plugin.

**Comment by ParkerM** [comment]
The settings become legible if you turn off the `popup.css` style sheet. Perhaps the issue is somewhere in there.

With popup.css enabled:
![image](https://user-images.githubusercontent.com/5124113/183269566-8eba4ab5-6f3d-4474-a6c0-c41f1914d628.png)


With popup.css disabled:
![image](https://user-images.githubusercontent.com/5124113/183269497-7e950d17-0961-493f-a32d-70ca629cb20e.png)

**Comment by ian-h-chamberlain** [comment]
Looking at the stylesheet https://github.com/plibither8/refined-hacker-news/blob/main/src/popup.styl#L6 it's not surprising that it becomes unreadable, since the colors look to be mostly hardcoded to a light background there.

Some potential options to fix might be:

* Update those colors to use `var()` like in the base style https://github.com/plibither8/refined-hacker-news/blob/main/src/webext-base.css#L67 
* just force the foreground colors to be dark, so they are at least readable on the default light background
* `@media (prefers-color-scheme: light)` around all the hardcoded colors (use defaults or alternatives in dark mode)
